### ISSUE TITLE
Jouw live link ontbreekt

### ISSUE THREAD

**Issue by KrijnHoetmer** [RickFDND/your-tribe-profile-card#2]
Dus ik heb geen idee hoe ik je site kan bekijken. Normale eindgebruikers lopen hier ook tegenaan :) Kijk eens bij [de instructies van de leertaak](https://github.com/fdnd-task/your-tribe-profile-card/blob/main/docs/visitekaartje-ontwerpen-maken-en-online-publiceren.md#aanpak-testfase) hoe je dit doet.

**Comment by RickFDND** [comment]
Ik heb de site toegevoegd. Thanks.
